version: '3.8'
services:
  middle:
    build: .
    command: python -u app.py
    ports: 
      - "5000:5001"
    volumes:
      - .:/backend
    links:
      - db
  db:
    image: mongo:latest
    hostname: backend_db
    environment:
      - MONGO_INITDB_DATABASE=subscribers_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
