version: '3.8'
services:
  db:
    image: mongo:latest
    hostname: backend_db
    environment:
      - MONGO_INITDB_DATABASE=subscribers_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
