version: '3.8'
services:
  broker1:
    build: .
    command: python -u app.py
    ports: 
      - "5101:5101"
    volumes:
      - .:/backend
    links:
      - db
  # broker2:
  #   build: .
  #   command: python -u broker2.py
  #   ports: 
  #     - "5102:5102"
  #   volumes:
  #     - .:/backend
  #   links:
  #     - db
  # broker3:
  #   build: .
  #   command: python -u broker3.py
  #   ports: 
  #     - "5103:5103"
  #   volumes:
  #     - .:/backend
  #   links:
  #     - db
  db:
    image: mongo:latest
    hostname: backend_db
    environment:
      - MONGO_INITDB_DATABASE=subscribers_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
