version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
  
  kafka-1:
    image: wurstmeister/kafka:latest
    container_name: kafka-1
    hostname: kafka-1
    ports:
      - 9091:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka-1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
  
  kafka-2:
    image: wurstmeister/kafka:latest
    container_name: kafka-2
    hostname: kafka-2
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka-2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

  kafka-3:
    image: wurstmeister/kafka:latest
    container_name: kafka-3
    hostname: kafka-3
    ports:
      - 9093:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka-3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
